### ISSUE TITLE
Ability to disable emergency mode

### ISSUE THREAD

**Issue by xyzroe** [xyzroe/ZigStarGW-FW#11]
Some people have problems with false activation of emergency mode when their local internet gateway does not respond to ping from ZigStar.

Add the ability to disable ping control or completely disable emergency mode.

**Comment by xyzroe** [comment]
duplicate https://github.com/xyzroe/ZigStarGW-FW/issues/13

**Comment by kubax** [comment]
Just wanted to leave a quick workaround for this "bug".

I (very) recently got myself a ZigStar device, and had the exact problem. I did manually configure the network and then had the problem with the emergency wifi enabled.

first of all, it would be better to have a configurable emergency wifi with encryption, but that might not be able on this device.

BUT to fix it until the option you mentioned is implemented, i did just enter a device as the gateway that does not route trafic (because i don't see any need for the zigstar device to reacht the internet) but that is always online. In my case i used a NAS device, but could be anything.

Maybe you could let us manually choose which device to ping to check if the device is up.

Also thanks for your work!

**Comment by xyzroe** [comment]
If your home network on which encryption is used is saved in the Wi-Fi settings, then when you turn on emergency mode, you will be connected to this network with encryption.

I see no practical point in creating an access point from ZigStar. Only for configuration, and there is no point in encryption.

You can allow ping from the local network on your gateway, all problems will be solved. There are no security issues with this.

Indeed, as one of the ways - use another device instead of a gateway.
Thanks for your advice to the community.

Perhaps in the future I will add a similar functionality.
Thanks for the ideas and feedback.

**Comment by xyzroe** [comment]
ZigStar is not recommended to use wifi in working mode. But it is possible.

Emergency mode turns on wifi in case of loss of wired connection.

If you have saved your network settings, ZigStar will first try to connect to it.
If successful, it will be connected as a client to your network until the wired connection is resumed.

If the wireless network is not available or no settings are saved, then ZigStar raises its access point.
After resuming the wired connection, it turns it off.

**Comment by monster1025** [comment]
Okay, so it works really strange now.
My gateway is responding to ping requests:
```
% ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=3.079 ms
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=3.306 ms
```

Here is my gateway status, it connected simultaneously to wifi and ethernet:
https://ibb.co/wMs4JR8

"Disable emergency mode (AP)" is disabled (not checked). Also here is config:
```
{"enableWiFi":1,"ssid":"****","pass":"*******","dhcpWiFi":1,"ip":"","mask":"","gw":"","disableEmerg":"0"}
```
According to Home Assistant status of gateway "Emergency mode = Off".
But it connected to wifi and ethernet same time.

**Comment by xyzroe** [comment]
I don't see anything strange.
You have the checkbox Enable Wi-Fi client mode checked
Therefore, there is a connection to the wifi, regardless of the state of the wired connection.

**Comment by monster1025** [comment]
Oh, missed it! thanks a lot!
