### ISSUE TITLE
Unable to turn off emergency WiFi

### ISSUE THREAD

**Issue by kolicheng** [xyzroe/ZigStarGW-FW#13]
Does anyone have the same problem? The ethernet can actually connect, but it shows disconnection.

**Comment by depuits** [comment]
I'm having the same issue. I've tried to disable emergency mode (AP) and setting a static ip in the network options but it keeps going to Emergency mode even though I am talking to it over ethernet.

**Comment by xyzroe** [comment]
First of all, let's understand why your device thinks that there is no wired network?
Because your default gateway is not responding to ping requests from ZigStar.
Fix it first.

About disabling emergency mode - to properly disable this mode your device must be NOT in emergency mode while setting this checkbox and saving config.

You can try to fix ping answers on default gateway, than remove this checkbox, save config, reboot device, set checkbox again.. After that emergency mode must not turning on.

**Comment by depuits** [comment]
Fixing the ping from the device did indeed fix it. As in https://github.com/mercenaruss/zigstar_gateways/issues/14 I had the device on an internet limited network which had no specified allow rule to the gateway and thus blocking the ping. I don't know if it is possible to just check if the device is connected using the ethernet port and if so just never to enable the emergency mode. That way the emergency mode would only enable when there is no physical link and no ap access. Currently its confusing that the checkbox only works when you would probably not feel the need to use the checkbox.

**Comment by xyzroe** [comment]
Unfortunately, the LAN chip (LAN8720A) used in ZigStar, does not always correctly return the state of the physical connection to the port, therefore, an additional gateway ping is used.
It was supposed to check the box at the time of the first device setup, and not at the time of the problem.
But your idea has been adopted.
