### ISSUE TITLE
Fails to boot after power outage.

### ISSUE THREAD

**Issue by flaektrem** [xyzroe/ZigStarGW-FW#14]
It seems like my GW (Zigstar LAN Gateway with 0.6.4 fw)) fails to boot correctly after power outage when the power returns.

I have done some testing and it seems like the GW is unable to boot properly if the switch its hooked up to not gets enough time to boot **BEFORE** the GW. That little green led on the ethernet port just glows a little at this moment.
After the switch is up and running i can power cycle the GW again and the led immediately lights up fully and connects.

Is there any solution for this? Suggestions?

**Comment by xyzroe** [comment]
If there is no cable connection at the time of startup, emergency mode will be activated after 30 seconds, unless otherwise specified in the settings.
The same as if the connection is disconnected while ZigStar is running.

If your network starts up for more than 30 seconds you can change [this setting](https://github.com/xyzroe/ZigStarGW-FW/blob/542995cb68386995f2e5deab4bc2b2f37b6334eb/src/config.h#L58
) for yourself.

**Comment by xyzroe** [comment]
No. You need to rebuild the FW yourself.
